Dev 11813 added integrations api
apono-io/terraform-provider-apono pull request #71
Opened 2024-06-13 20:59 UTC by SemyonM-Apono

2024-06-19 12:22 UTC, tomerstein requested changes
Good job, lets make few changes

2024-06-19 12:22 UTC, tomerstein commented on internal/models/integration.go
> +		var AttributeValue = make([]types.String, len(in.AttributeValue))
```suggestion
		var attributeValue = make([]types.String, len(in.AttributeValue))
```
camel case for variable names, please adjust the rest of the code accordingly.

2024-06-19 12:22 UTC, tomerstein commented on internal/models/integration.go
> +		for j, av := range in.AttributeValue {
same as before, lets not use index and give more readable names to the iterators

2024-06-19 12:22 UTC, tomerstein commented on internal/models/integration.go
> +		}
```suggestion
		IntegrationId := basetypes.NewStringPointerValue(in.IntegrationId.Get())
```
this code can be simplify with using the pointer to init the variable

2024-06-19 12:22 UTC, tomerstein commented on internal/models/integration.go
> +
same about arguments and variables in camel case

2024-06-19 13:31 UTC, SemyonM-Apono commented on internal/mockserver/Integrations.go
> +	httpmock.RegisterResponder(http.MethodDelete, `=~^http://api\.apono\.dev/api/v2/integrations/([^/]+)\z`, func(req *http.Request) (*http.Response, error) {
No it's actually correct. There's no delete endpoint in the new TF API. Upon design step we agreed that we keep delete.

2024-06-19 13:57 UTC, SemyonM-Apono commented on internal/mockserver/Integrations.go
> +	httpmock.RegisterResponder(http.MethodGet, `=~^http://api\.apono\.dev/api/v2/integrations-catalog/([^/]+)\z`, func(req *http.Request) (*http.Response, error) {
As agreed - moving to own setup api

2024-06-20 14:08 UTC, tomerstein approved these changes

2024-06-20 14:08 UTC, tomerstein commented on internal/provider/resource_integration.go
> +			"`resource_owner_mappings` cannot be set unless `integration_owners` is also set.",
you can define integration owner without resource owners? if so this validation is not good, if not lets change the message to be more like "both field must be set together"

2024-06-23 10:30 UTC, merged